Simulink.defineIntEnumType( 'ComMMode', ...
   {'COMM_FULL_COMMUNICATION','COMM_NO_COMMUNICATION','COMM_SILENT_COMMUNICATION'}, ...
   [0 1 2], ...
   'DefaultValue', 'COMM_NO_COMMUNICATION', ...
   'StorageType', 'uint8', ...
   'Description', 'Type definition of ComMMode.', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

Simulink.defineIntEnumType( 'ComM_ModeType', ...
   {'COMM_NO_COMMUNICATION','COMM_SILENT_COMMUNICATION','COMM_FULL_COMMUNICATION'}, ...
   [0 1 2], ...
   'DefaultValue', 'COMM_NO_COMMUNICATION', ...
   'Description', 'Type definition of ComM_ModeType.', ...
   'HeaderFile', 'Rte_Type.h', ...
   'AddClassNameToEnumNames', false);

